# Generated by Django 5.1.6 on 2025-02-09 12:53

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Update Time')),
                ('is_deleted', models.BooleanField(db_default=django.db.models.functions.datetime.Now(), default=False, verbose_name='Deletion Flag')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('birth_date', models.DateField(db_default=django.db.models.functions.datetime.Now(), db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Update Time')),
                ('is_deleted', models.BooleanField(db_default=django.db.models.functions.datetime.Now(), default=False, verbose_name='Deletion Flag')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('published_date', models.DateField(db_default=django.db.models.functions.datetime.Now(), db_index=True, default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Update Time')),
                ('is_deleted', models.BooleanField(db_default=django.db.models.functions.datetime.Now(), default=False, verbose_name='Deletion Flag')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('books', models.ManyToManyField(to='bookstore.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Update Time')),
                ('is_deleted', models.BooleanField(db_default=django.db.models.functions.datetime.Now(), default=False, verbose_name='Deletion Flag')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('books', models.ManyToManyField(to='bookstore.book')),
                ('publishers', models.ManyToManyField(to='bookstore.publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
